language: ruby
cache: 
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: |
  bundle exec jekyll build && bundle exec htmlproofer ./_site \
  --assume-extension \
  --empty-alt-ignore \
  --alt-ignore '/.*/' \
  --file-ignore ./_site/assets/obo-t17800628-33.html \
  --timeframe '30d'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
