name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.org
baseurl: jekyll/
permalink: :categories/:title
exclude:
  - deprecated
  - vendor
  - Gemfile
  - Gemfile.lock
  - Procfile
safe: true
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  - 
    scope:
      path: "es"
    values:
      lang: "es"
    
