name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.org
permalink: :categories/:title
exclude: [deprecated]
safe: true
pygments: true
markdown: redcarpet
gems:
  - jekyll-redirect-from
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']

