name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
# Used to insert the live url of the site in places that require a full link such as suggested citations and XML feed
liveurl: https://programminghistorian.org
baseurl: ""
permalink: :categories/:title
exclude:
  - deprecated
  - vendor
  - Gemfile
  - Gemfile.lock
highlighter: rouge
markdown: kramdown
permalink: :categories/:title
future: true
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      basepath: ""
      lessonpath: "/lessons"
  -
    scope:
      path: "es"
    values:
      lang: "es"
      basepath: "/es"
      lessonpath: "/lecciones"
  -
    scope:
      path: "lessons"
    values:
      lesson: true
      english-lesson: true
  -
    scope:
      path: "lessons/retired"
    values:
      lesson: false
      english-lesson: false
  -
    scope:
      path: "es/lecciones"
    values:
      translated-lesson: true
      lesson: true
  -
    scope:
      path: _posts
    values:
      category: posts

# For local work: bundle exec jekyll serve --watch --baseurl '/proghistdev' or wherever else your local site is located
